# Generated by Django 5.1.2 on 2024-10-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfaultmodel',
            name='Fault_Id',
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='Fault_Restored_Date_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='OFC_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='OFC_Used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='PLB_Used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='SJC_Used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='Trial_Pit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
