# Generated by Django 5.1.2 on 2024-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfault', '0002_remove_bookfaultmodel_fault_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfaultmodel',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
