# Generated by Django 5.1.2 on 2024-10-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfault', '0004_alter_bookfaultmodel_ofc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='OFC_Type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='OFC_Used',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='PLB_Used',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='SJC_Used',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='Trench',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='Trial_Pit',
            field=models.CharField(default='', max_length=2),
        ),
    ]
