# Generated by Django 5.1.2 on 2024-11-02 05:05

import bookfault.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookfault', '0005_alter_bookfaultmodel_ofc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='Fault_Restored_Date_Time',
            field=bookfault.fields.FormattedDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookfaultmodel',
            name='Reporting_date_time',
            field=bookfault.fields.FormattedDateTimeField(),
        ),
    ]
