# Generated by Django 5.1.2 on 2024-11-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfault', '0006_alter_bookfaultmodel_fault_restored_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfaultmodel',
            name='Total_downtime',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
