# Generated by Django 5.1.2 on 2024-11-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfault', '0010_alter_bookfaultmodel_admin_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfaultmodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bookfaultmodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
